name: TEST::A test workflow to test how to model the github action
on:
  create:
    tags:
      - dev-*

jobs:
  deploy:
    if: ${{ startsWith(github.ref, 'refs/tags/dev-') }}
    runs-on: ubuntu-latest
    steps:
      - name: Test Echo
        run: |
          date
